name: dhahabu
description: Gold trade platform for Miners, Dealers & Government
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^2.0.0
  http: ^1.2.2
  shared_preferences: ^2.3.3
  provider: ^6.1.2
  intl: ^0.20.3
  google_fonts: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
