# Generated by Django 6.1.1 on 2026-10-02 15:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('karat', models.CharField(choices=[('24K', '24 Karat'), ('22K', '22 Karat'), ('18K', '18 Karat')], max_length=5)),
                ('price_per_gram', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='TZS', max_length=5)),
                ('source', models.CharField(blank=True, default='Manual', max_length=100)),
                ('effective_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prices_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gold_prices',
                'ordering': ['-effective_at'],
                'indexes': [models.Index(fields=['karat', '-effective_at'], name='gold_prices_karat_807a24_idx')],
            },
        ),
    ]
