# Generated by Django 6.1.1 on 2026-10-05 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='goldprice',
            name='gold_prices_karat_807a24_idx',
        ),
        migrations.AlterField(
            model_name='goldprice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='goldprice',
            name='karat',
            field=models.CharField(choices=[('24K', '24K'), ('22K', '22K'), ('18K', '18K')], max_length=5),
        ),
    ]
