# Generated by Django 6.1.1 on 2026-10-05 09:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight_grams', models.DecimalField(decimal_places=3, max_digits=10)),
                ('karat', models.CharField(choices=[('24K', '24K'), ('22K', '22K'), ('18K', '18K')], max_length=5)),
                ('asking_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('price_per_gram', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('open', 'Open'), ('sold', 'Sold'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='listings/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('miner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'listings',
                'ordering': ['-created_at'],
            },
        ),
    ]
