# Generated by Django 6.1.1 on 2026-10-02 15:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight_grams', models.DecimalField(decimal_places=3, max_digits=10)),
                ('karat', models.CharField(choices=[('24K', '24K'), ('22K', '22K'), ('18K', '18K')], max_length=5)),
                ('price_per_gram', models.DecimalField(decimal_places=2, max_digits=12)),
                ('agreed_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_confirm', 'Pending Miner Confirm'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending_confirm', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('client_ref', models.CharField(blank=True, db_index=True, max_length=64)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_created', to=settings.AUTH_USER_MODEL)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases_as_dealer', to=settings.AUTH_USER_MODEL)),
                ('miner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_as_miner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('royalty_rate', models.DecimalField(decimal_places=4, max_digits=5)),
                ('royalty_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tax_base', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='TZS', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_reversal', models.BooleanField(default=False)),
                ('reverses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='transactions.taxrecord')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='tax_record', to='transactions.transaction')),
            ],
            options={
                'db_table': 'tax_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['miner', '-created_at'], name='transaction_miner_i_69a630_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['dealer', '-created_at'], name='transaction_dealer__c43226_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', '-created_at'], name='transaction_status_b84006_idx'),
        ),
    ]
