# Generated by Django 6.1.1 on 2026-10-05 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxrecord',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='transaction_miner_i_69a630_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='transaction_dealer__c43226_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='transaction_status_b84006_idx',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='taxrecord',
            name='reverses',
        ),
        migrations.AddField(
            model_name='transaction',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='listings.listing'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending_confirm', 'Pending Confirm'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('rejected_conflict', 'Rejected Conflict')], default='pending_confirm', max_length=20),
        ),
    ]
